# Generated by Django 4.1.1 on 2022-11-03 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import programmodule.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=programmodule.models.course_images)),
                ('created_at', models.DateField(default=datetime.date.today, editable=False, verbose_name='Date')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=programmodule.models.program_images)),
                ('created_at', models.DateField(default=datetime.date.today, editable=False, verbose_name='Date')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('VIDEO', 'Video'), ('DOCUMENT', 'Document'), ('ASSIGNMENT', 'Assignment')], max_length=255)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(default=datetime.date.today, editable=False, verbose_name='Date')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coursecontent', to='programmodule.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courseprogram', to='programmodule.programs'),
        ),
    ]
