# Generated by Django 4.1.1 on 2022-11-03 08:10

import classmodule.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=255, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('attendance_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(default='', max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('title', models.CharField(default='', max_length=255)),
                ('year', models.IntegerField(blank=True, default=0, null=True, verbose_name='year')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='inactive', max_length=255)),
                ('created_at', models.DateField(default=datetime.date.today, editable=False, verbose_name='Date')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='', max_length=255)),
                ('timeStamp', models.DateTimeField(default=classmodule.models.get_time)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classmodule.class')),
            ],
        ),
    ]
