# Generated by Django 4.1.1 on 2022-11-03 08:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teachermodule.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('cnic', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('qualification', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=teachermodule.models.teacher_images)),
                ('status', models.CharField(choices=[('Current', 'Current'), ('Retired', 'Retired')], default='Current', max_length=255)),
                ('created_at', models.DateField(default=datetime.date.today, editable=False, verbose_name='Date')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacheruser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
