# Generated by Django 4.1.1 on 2022-11-03 08:10

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import librarymodule.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('url', models.URLField(max_length=255)),
                ('type', models.CharField(choices=[('Book', 'Book'), ('Magazines', 'Magazines'), ('Multimedia', 'Multimedia'), ('Others', 'Others')], max_length=255)),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=librarymodule.models.library_images)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), default=list, size=None)),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=librarymodule.models.library_files)),
                ('created_at', models.DateField(default=datetime.date.today, editable=False, verbose_name='Date')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('url', models.URLField(max_length=255)),
                ('type', models.CharField(blank=True, choices=[('Book', 'Book'), ('Magazines', 'Magazines'), ('Multimedia', 'Multimedia'), ('Others', 'Others')], max_length=255, null=True)),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=librarymodule.models.publication_images)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, null=True, size=None)),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=librarymodule.models.publication_files)),
                ('created_at', models.DateField(default=datetime.date.today, editable=False, verbose_name='Date')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('description', tinymce.models.HTMLField()),
                ('url', models.URLField(max_length=255)),
                ('type', models.CharField(blank=True, choices=[('Video', 'Video'), ('Audio', 'Audio'), ('Document', 'Document')], max_length=255, null=True)),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=librarymodule.models.resource_images)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), blank=True, null=True, size=None)),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=librarymodule.models.resource_files)),
                ('created_at', models.DateField(default=datetime.date.today, editable=False, verbose_name='Date')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
